#! /usr/bin/env bash

# MGH 2009-05-29: Remove packing commands because I think the packing is affecting
# the accuracy of stream function calculations
#

set -e

echo Switching to $(workpath)
cd $(workpath)

for i in "$@"
do

  s=$(printf %4.4d ${i})

  echo Record-averaging roms_avg_${s}.nc to roms_avg_${s}_a10.nc
  roms_avg -n 10 roms_avg_${s}.nc

  if test ${i} -gt 1
  then
    echo Trimming first record from roms_his_${s}.nc
    ncks -O -d ocean_time,1, roms_his_${s}.nc roms_his_${s}.nc
  fi

  if test ${i} -gt 1
  then
    echo Trimming first record from roms_sta_${s}.nc
    ncks -O -d ocean_time,1, roms_sta_${s}.nc roms_sta_${s}.nc
  fi

done
